/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	cephrookiov1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNvmeOfOSDs implements NvmeOfOSDInterface
type FakeNvmeOfOSDs struct {
	Fake *FakeCephV1
	ns   string
}

var nvmeofosdsResource = schema.GroupVersionResource{Group: "ceph.rook.io", Version: "v1", Resource: "nvmeofosds"}

var nvmeofosdsKind = schema.GroupVersionKind{Group: "ceph.rook.io", Version: "v1", Kind: "NvmeOfOSD"}

// Get takes name of the nvmeOfOSD, and returns the corresponding nvmeOfOSD object, and an error if there is any.
func (c *FakeNvmeOfOSDs) Get(ctx context.Context, name string, options v1.GetOptions) (result *cephrookiov1.NvmeOfOSD, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nvmeofosdsResource, c.ns, name), &cephrookiov1.NvmeOfOSD{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.NvmeOfOSD), err
}

// List takes label and field selectors, and returns the list of NvmeOfOSDs that match those selectors.
func (c *FakeNvmeOfOSDs) List(ctx context.Context, opts v1.ListOptions) (result *cephrookiov1.NvmeOfOSDList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nvmeofosdsResource, nvmeofosdsKind, c.ns, opts), &cephrookiov1.NvmeOfOSDList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &cephrookiov1.NvmeOfOSDList{ListMeta: obj.(*cephrookiov1.NvmeOfOSDList).ListMeta}
	for _, item := range obj.(*cephrookiov1.NvmeOfOSDList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nvmeOfOSDs.
func (c *FakeNvmeOfOSDs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nvmeofosdsResource, c.ns, opts))

}

// Create takes the representation of a nvmeOfOSD and creates it.  Returns the server's representation of the nvmeOfOSD, and an error, if there is any.
func (c *FakeNvmeOfOSDs) Create(ctx context.Context, nvmeOfOSD *cephrookiov1.NvmeOfOSD, opts v1.CreateOptions) (result *cephrookiov1.NvmeOfOSD, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nvmeofosdsResource, c.ns, nvmeOfOSD), &cephrookiov1.NvmeOfOSD{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.NvmeOfOSD), err
}

// Update takes the representation of a nvmeOfOSD and updates it. Returns the server's representation of the nvmeOfOSD, and an error, if there is any.
func (c *FakeNvmeOfOSDs) Update(ctx context.Context, nvmeOfOSD *cephrookiov1.NvmeOfOSD, opts v1.UpdateOptions) (result *cephrookiov1.NvmeOfOSD, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nvmeofosdsResource, c.ns, nvmeOfOSD), &cephrookiov1.NvmeOfOSD{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.NvmeOfOSD), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNvmeOfOSDs) UpdateStatus(ctx context.Context, nvmeOfOSD *cephrookiov1.NvmeOfOSD, opts v1.UpdateOptions) (*cephrookiov1.NvmeOfOSD, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(nvmeofosdsResource, "status", c.ns, nvmeOfOSD), &cephrookiov1.NvmeOfOSD{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.NvmeOfOSD), err
}

// Delete takes name of the nvmeOfOSD and deletes it. Returns an error if one occurs.
func (c *FakeNvmeOfOSDs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nvmeofosdsResource, c.ns, name), &cephrookiov1.NvmeOfOSD{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNvmeOfOSDs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nvmeofosdsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &cephrookiov1.NvmeOfOSDList{})
	return err
}

// Patch applies the patch and returns the patched nvmeOfOSD.
func (c *FakeNvmeOfOSDs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *cephrookiov1.NvmeOfOSD, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nvmeofosdsResource, c.ns, name, pt, data, subresources...), &cephrookiov1.NvmeOfOSD{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.NvmeOfOSD), err
}
