/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	cephrookiov1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNvmeOfStorages implements NvmeOfStorageInterface
type FakeNvmeOfStorages struct {
	Fake *FakeCephV1
	ns   string
}

var nvmeofstoragesResource = schema.GroupVersionResource{Group: "ceph.rook.io", Version: "v1", Resource: "nvmeofstorages"}

var nvmeofstoragesKind = schema.GroupVersionKind{Group: "ceph.rook.io", Version: "v1", Kind: "NvmeOfStorage"}

// Get takes name of the nvmeOfStorage, and returns the corresponding nvmeOfStorage object, and an error if there is any.
func (c *FakeNvmeOfStorages) Get(ctx context.Context, name string, options v1.GetOptions) (result *cephrookiov1.NvmeOfStorage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nvmeofstoragesResource, c.ns, name), &cephrookiov1.NvmeOfStorage{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.NvmeOfStorage), err
}

// List takes label and field selectors, and returns the list of NvmeOfStorages that match those selectors.
func (c *FakeNvmeOfStorages) List(ctx context.Context, opts v1.ListOptions) (result *cephrookiov1.NvmeOfStorageList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nvmeofstoragesResource, nvmeofstoragesKind, c.ns, opts), &cephrookiov1.NvmeOfStorageList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &cephrookiov1.NvmeOfStorageList{ListMeta: obj.(*cephrookiov1.NvmeOfStorageList).ListMeta}
	for _, item := range obj.(*cephrookiov1.NvmeOfStorageList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nvmeOfStorages.
func (c *FakeNvmeOfStorages) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nvmeofstoragesResource, c.ns, opts))

}

// Create takes the representation of a nvmeOfStorage and creates it.  Returns the server's representation of the nvmeOfStorage, and an error, if there is any.
func (c *FakeNvmeOfStorages) Create(ctx context.Context, nvmeOfStorage *cephrookiov1.NvmeOfStorage, opts v1.CreateOptions) (result *cephrookiov1.NvmeOfStorage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nvmeofstoragesResource, c.ns, nvmeOfStorage), &cephrookiov1.NvmeOfStorage{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.NvmeOfStorage), err
}

// Update takes the representation of a nvmeOfStorage and updates it. Returns the server's representation of the nvmeOfStorage, and an error, if there is any.
func (c *FakeNvmeOfStorages) Update(ctx context.Context, nvmeOfStorage *cephrookiov1.NvmeOfStorage, opts v1.UpdateOptions) (result *cephrookiov1.NvmeOfStorage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nvmeofstoragesResource, c.ns, nvmeOfStorage), &cephrookiov1.NvmeOfStorage{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.NvmeOfStorage), err
}

// Delete takes name of the nvmeOfStorage and deletes it. Returns an error if one occurs.
func (c *FakeNvmeOfStorages) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nvmeofstoragesResource, c.ns, name), &cephrookiov1.NvmeOfStorage{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNvmeOfStorages) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nvmeofstoragesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &cephrookiov1.NvmeOfStorageList{})
	return err
}

// Patch applies the patch and returns the patched nvmeOfStorage.
func (c *FakeNvmeOfStorages) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *cephrookiov1.NvmeOfStorage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nvmeofstoragesResource, c.ns, name, pt, data, subresources...), &cephrookiov1.NvmeOfStorage{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cephrookiov1.NvmeOfStorage), err
}
