/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
	scheme "github.com/rook/rook/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NvmeOfOSDsGetter has a method to return a NvmeOfOSDInterface.
// A group's client should implement this interface.
type NvmeOfOSDsGetter interface {
	NvmeOfOSDs(namespace string) NvmeOfOSDInterface
}

// NvmeOfOSDInterface has methods to work with NvmeOfOSD resources.
type NvmeOfOSDInterface interface {
	Create(ctx context.Context, nvmeOfOSD *v1.NvmeOfOSD, opts metav1.CreateOptions) (*v1.NvmeOfOSD, error)
	Update(ctx context.Context, nvmeOfOSD *v1.NvmeOfOSD, opts metav1.UpdateOptions) (*v1.NvmeOfOSD, error)
	UpdateStatus(ctx context.Context, nvmeOfOSD *v1.NvmeOfOSD, opts metav1.UpdateOptions) (*v1.NvmeOfOSD, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.NvmeOfOSD, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.NvmeOfOSDList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.NvmeOfOSD, err error)
	NvmeOfOSDExpansion
}

// nvmeOfOSDs implements NvmeOfOSDInterface
type nvmeOfOSDs struct {
	client rest.Interface
	ns     string
}

// newNvmeOfOSDs returns a NvmeOfOSDs
func newNvmeOfOSDs(c *CephV1Client, namespace string) *nvmeOfOSDs {
	return &nvmeOfOSDs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nvmeOfOSD, and returns the corresponding nvmeOfOSD object, and an error if there is any.
func (c *nvmeOfOSDs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.NvmeOfOSD, err error) {
	result = &v1.NvmeOfOSD{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nvmeofosds").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NvmeOfOSDs that match those selectors.
func (c *nvmeOfOSDs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.NvmeOfOSDList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.NvmeOfOSDList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nvmeofosds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nvmeOfOSDs.
func (c *nvmeOfOSDs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nvmeofosds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a nvmeOfOSD and creates it.  Returns the server's representation of the nvmeOfOSD, and an error, if there is any.
func (c *nvmeOfOSDs) Create(ctx context.Context, nvmeOfOSD *v1.NvmeOfOSD, opts metav1.CreateOptions) (result *v1.NvmeOfOSD, err error) {
	result = &v1.NvmeOfOSD{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nvmeofosds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nvmeOfOSD).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a nvmeOfOSD and updates it. Returns the server's representation of the nvmeOfOSD, and an error, if there is any.
func (c *nvmeOfOSDs) Update(ctx context.Context, nvmeOfOSD *v1.NvmeOfOSD, opts metav1.UpdateOptions) (result *v1.NvmeOfOSD, err error) {
	result = &v1.NvmeOfOSD{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nvmeofosds").
		Name(nvmeOfOSD.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nvmeOfOSD).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *nvmeOfOSDs) UpdateStatus(ctx context.Context, nvmeOfOSD *v1.NvmeOfOSD, opts metav1.UpdateOptions) (result *v1.NvmeOfOSD, err error) {
	result = &v1.NvmeOfOSD{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nvmeofosds").
		Name(nvmeOfOSD.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nvmeOfOSD).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the nvmeOfOSD and deletes it. Returns an error if one occurs.
func (c *nvmeOfOSDs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nvmeofosds").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nvmeOfOSDs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nvmeofosds").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched nvmeOfOSD.
func (c *nvmeOfOSDs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.NvmeOfOSD, err error) {
	result = &v1.NvmeOfOSD{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nvmeofosds").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
